### ISSUE TITLE
Suggestion to add TPM command spec references into "commands.rs" file.

### ISSUE THREAD

**Issue by TRJensen** [tpm-rs/tpm-rs#109]
Idea is simply to refer to latest TPM 2.0 1.83 Part 3 Commands specification.

For example:

<pre>
// ============================================================================
// 32 Attached Components [TPM2.0 1.83]
// ============================================================================

// 32.2 TPM2_AC_GetCapability

&lt; ... request and response struct here ... &gt;

// 32.3 TPM2_AC_Send

// 32.4 TPM2_Policy_AC_SendSelect
</pre>

This helps keeping command request and response definitions sorted as pr specification, and make it easy to search definition based in naming from specification.

**Comment by oddcoder** [comment]
I think it will be better if we add them as [rutdoc](https://doc.rust-lang.org/rustdoc/index.html) comments, ideally with one doc test per command. What do you think ?

**Comment by chrisfenner** [comment]
I'm a big fan of any form of this idea (not being too familiar with rustdoc myself). One obvious challenge is that numbering of sections in the spec can change from version to version. Let me take an action item back to TCG to see if some stable links could ever exist in the PDFs. Otherwise, giving the current number along with section name seems like the best we can do (it's what go-tpm does) and it really does help humans double check when things are supposed to be 1:1 with the specification.

**Comment by oddcoder** [comment]
I noticed that tpm specs also exist as markdown, will it ever be possible to have them in some web format ?

**Comment by chrisfenner** [comment]
There's an internal conversion to Markdown completing ~now, which means output to Web in the future would be possible. However, that effort is currently not staffed, in case you have some free time :)

**Comment by TRJensen** [comment]
I agree that it would be great to have fixed reference in TPM spec. But then again - there were 5 years between 1.64 and 1.83 - 3 years before according to my colleague - which means it is an OK fairly simple task to update - as long as we are limited to have the spec references few places :slightly_smiling_face: I agree with @oddcoder to add rust comments - I initially did that using /// slashes but got error where there were were only empty lines afterwards - i need to check again.
