### ISSUE TITLE
Fully eliminate unsafe code

### ISSUE THREAD

**Issue by oddcoder** [tpm-rs/tpm-rs#79]
While reviewing code, I noticed we do actually have one instance of `unsafe { }`  in [marshal-derive](https://github.com/tpm-rs/tpm-rs/blob/79fea7271a74b3442e0eb734a1eb022f13c1c848/marshal-derive/src/lib.rs#L149). Apparently 
`#![forbid(unsafe_code)]` doesn't apply for macros, let alone proc-macros.

Ideally we'd want to do two things:
1- see if we can replace the unsafe code with safe one. Quick assessment shows it is possible.
2- keep track of current rust  development regarding unsafe hygiene for macros. According to [this](https://internals.rust-lang.org/t/hidden-unsafe-due-to-unintentionally-abusable-macros-and-include/14107/60) and [that](https://internals.rust-lang.org/t/explicitly-marking-unsafe-macro-expressions/9425), it look  there is no current way to prevent unsafe code from rust macros.

**Comment by trent-reed** [comment]
Yeah this should be pretty easy to turn into a codegen match statement.

I really wish there was an approved safe way to get the discriminant of an enum, but currently this is actually the best way. I'm fine either with changing it to a match statement though and revisiting this in the future if it causes code bloat issues.

**Comment by oddcoder** [comment]
hmmm, I mistakenly thought that `as` cast would suffice. Apparently this only works when the variants contains no structs to tuples. I think we have three possible options two of which you already suggested:
1- Leave it as it is and just keep the issue open until rust fixes it.
2- Eliminate the unsafe block by generating match, it will be interesting to see if the compiler will optimize the match out, But I don't think it matters for our case.
3- Isolate this behavior outside github repo into a small repo with a single crate that does this one job of deriving discriminates and generate compiler error for the undefined case.

I don't have a particular preference especially that I realized that `_ as _` is no longer an option. Each option has some disadvantages. If you have preference let me know! if not, we can just leave it for later.

It is a unlikely, but I can look around, perhaps the solution already exists in rust nightly, with a roadmap for stabilization.

**Comment by trent-reed** [comment]
I spent some time looking around myself, because I noticed the oddity of having that little chunk of unsafe code much like you did - the best I found is that there's some discussions going on around cleaning up `as` moving forward for future versions of rust, but it looked at the time like those were still in pretty early discussions.

* https://users.rust-lang.org/t/enum-crimes-getting-the-discriminant/88103
* https://internals.rust-lang.org/t/enums-should-magically-get-a-trait-for-getting-discriminant-and-variant-count/18434
* https://github.com/rust-lang/rust/issues/60553#issuecomment-1374949390
* https://github.com/rust-lang/rust/issues/86772

**Comment by oddcoder** [comment]
I am thinking the best of all approaches would be to isolate the discriminant calculation in a separate crate & repo. The idea would be  to separate it from the rest of `tpm-rs` so it can be easily audited.

The idea would be to have trait for `Discriminant` that calculates `discriminant` exactly like it is done here, but for the macro system to only it to be derived for the cases when there is no UB.

It shouldn't be fundamentally more secure  than what we are doing, but it feels better isolated. similar to how zerocopy is isolated from every project that uses it.

I cannot create repos in tmp-rs org, so I will try to rollup a small one and move it to tpm-rs org when it is done, but I am also interested in your opinion on this. I not fully 100% sure we should do this because it is a trivial usage of `unsafe{ }`

**Comment by oddcoder** [comment]
@trent-reed 

I did a small poc for [isolating the discriminant part](https://github.com/oddcoder/safe-discriminant) I tried getting [some feedback](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/feedback.20request.3A.20safe.20discriminant.20extraction.20from.20enums) for it from people who are more familiar with unsafe rust than myself. It seams there is no substantial problem.  Feel free to give it a look.

I tried adapting this crate to `tpm-rs` but it would make sense to only do so after #84 because then we can have `MarshalableEnum: Discriminant` and that would remove big chunk of marshalling logic.


The plan from my side would be after #84 to:
1- submit patch here replacing unsafe code with the `safe-discriminant`.
2- if it looks good and make sense, we can move safe-discriminant to https://github.com/tpm-rs, publish it on crates.io and use it instead of the github based cargo dependency.

**Comment by trent-reed** [comment]
Yeah, I agree that this is something that should eventually be provided by the standard in some manner - it's a bit silly that we have to do this, but I get it there's a lot to think about here and the language probably doesn't want to make any early wrong turns...

Anyways, I'm fine with taking such a dependency until the rust std provides a better option. Note that the impact this'll have on clients is they must also add a derive for `Discriminant`, but that's probably fine.

I have some feedback on the code though if you want it:

1. According to documentation, this is the list of all the types that can be accessed using this method for enum primitive representations: https://doc.rust-lang.org/reference/type-layout.html#primitive-representations; I see that you saw that in your documentation, but it seems your list of primitives is smaller than the list presented here.
2. When it lands in stable, you may want to have the discriminant associated type use https://doc.rust-lang.org/std/num/trait.ZeroablePrimitive.html instead, which is probably a bit more accurate and includes `Copy`.
3. `Selector` is terminology that originates from the TPM specification actually, so I'm not sure how wise it is to use in this very generic context.
4. It's not clear to me, and my experience specifically with proc-macros and generics is limited, but it might be good to add a test that has an enum with a trait bounds on the enum generic and see if it still works, like this:

```rs
enum Test<'lifetime, T: SomeTrait + 'otherlifetime> {
  A(T) = 1,
  B(&'lifetime str) = 2,
  // ... etc. ...
}
```

5. There's a small typo in your documentation "evenbe" instead of "even be".
6. The compiler is suggesting that it's a warning not a compiler error if multiple repr primitives are provided according to your test stderr (unless I'm misreading this?): https://github.com/oddcoder/safe-discriminant/blob/main/safe-discriminant/tests/fail/multi_repr.stderr - we should probably make this a hard error for the derive macro.
7. (Optional) Just some stylistic nits, here's some changes I'd make to the code relating to variant validation:

```rs
use syn::{spanned::Spanned, Error, Result, Variant};

fn valiate_single_variant(v: Variant) -> Option<Error> {
    match v.discriminant {
        Some(_) => None,
        None => Some(Error::new(v.span(), concat!(
            "Missing explicit discriminant. Note: If you want to reason about ",
            "discriminants, but do not care about concrete values, consider ",
            "using `core::mem::Discriminant` instead."
        ))),
    }
}

fn validate_all_variants(variants: impl Iterator<Item = Variant>) -> Result<()> {
    variants
        .filter_map(valiate_single_variant)
        .reduce(|mut acc, e| { acc.combine(e); acc })
        .map(|e| Err(e))
        .unwrap_or(Ok(()))
}
```

**Comment by trent-reed** [comment]
Also, should we find an open issue that we can track for proper std support? Every issue I find is closed...

**Comment by trent-reed** [comment]
Also also - I forgot to say, but thank you for putting this together! :)

**Comment by oddcoder** [comment]
> it seems your list of primitives is smaller than the list presented here.

I missed a couple of them. I added `i128` and `u128` but I kept `usize` and `isize` out. I am slightly concerned about discriminant with sizes that depend on platform. If anyone really required them, we can look at them again.

> Selector is terminology that originates from the TPM specification actually, so I'm not sure how wise it is to use in this very generic context.

Feel free to suggest any name, I thought about `Discriminant` and `Tag` as names but I did't like any and I have no on in mind.

> but it might be good to add a test that has an enum with a trait bounds on the enum generic and see if it still works

Unfortunately this particular case will not  work as is, it will require too much processing on the generics and I slightly prefer keeping the crate simple, especially that it will eventually be cargo-yanked. But slightly rewrite will make it work:

```rust
pub enum Foo<'a, T>
where
    T: 'a,
...
``` 
> The compiler is suggesting that it's a warning not a compiler error if multiple repr primitives are provided according to your test stderr.

Their wording is a bit confusing. So right now it is a soft error [E0566](https://doc.rust-lang.org/stable/error_codes/E0566.html). Given that this was old acceptable behavior, they make it soft error first (can be disabled), then they make it hard error. But realistically, if someone goes to the trouble of adding `#[allow(conflicting_repr_hints)]`, they are on their own.

> Just some stylistic nits, here's some changes I'd make to the code relating to variant validation

I like it thanks!

**Comment by oddcoder** [comment]
> Also, should we find an open issue that we can track for proper std support? Every issue I find is closed...

I am not sure if issues are how they track new features, there is https://github.com/rust-lang/rfcs/pull/3607 and it is not even accepted as an RFC, which means it is going to be a long long time until this lands in stable.

**Comment by oddcoder** [comment]
@trent-reed if you have time feel free to give safe-disc another look, if all looks good to you, I can put it on crates.io.

I tried moving it here but it is [a bit tricky](https://github.com/orgs/tpm-rs/discussions/21) ... so it might take longer than needed.

**Comment by trent-reed** [comment]
Thanks!

> I missed a couple of them. I added `i128` and `u128` but I kept `usize` and `isize` out. I am slightly concerned about discriminant with sizes that depend on platform. If anyone really required them, we can look at them again.

That's fair, I guess my thought process was that it's not necessarily wrong to use them, it just depends on what they do with them. But we can start with them not being exposed and see if someone asks for it.

> Feel free to suggest any name, I thought about `Discriminant` and `Tag` as names but I did't like any and I have no on in mind.

Hmm, ideally we'd just name this something like `Type`, that way folks can say stuff like `Discriminant<Type=...>`; But that's such a generic name and might cause other troubles. Maybe since it has to do with the representation we can simply call it that (`Discriminant<Repr=...>`)?

What do you think of `Repr` since that ties it closer to `#[repr()]` or maybe more explicitly `Representation`?

I'm honestly not digging any of these, maybe a slight preference for `Repr`, but up to you.

> Unfortunately this particular case will not work as is, it will require too much processing on the generics and I slightly prefer keeping the crate simple, especially that it will eventually be cargo-yanked.

That's fine, I guess I was thinking if it's a general solution and we don't know when a fix is coming, we should probably support it very generally. I guess that comes back to depending on if it should be explicitly for us, or for anyone who runs into this problem.

Personally, I'm slightly in favour of fully supporting this, but if you want I can contribute to do so.

And yes, maybe my example wasn't perfect, but my point was there are a few edge-cases here I don't think it handles.

* Explicitly named lifetimes (`enum Test<'a>`)
* Explicitly named lifetimes with bounds (`enum Test<'a, 'b: 'a>`)
* Generics with trait bouds (`enum Test<T: Trait>`)
* Generics with lifetime (`enum Test<'a, T: Trait<'a>>` or `enum Test<'a, T: Trait + 'a>`)

We can start simple, and see if others need more, or iteratively make it better.

> Their wording is a bit confusing. So right now it is a soft error [E0566](https://doc.rust-lang.org/stable/error_codes/E0566.html). Given that this was old acceptable behavior, they make it soft error first (can be disabled), then they make it hard error. But realistically, if someone goes to the trouble of adding `#[allow(conflicting_repr_hints)]`, they are on their own.

Ah I see, I guess my point is you have this section of code:

```rs
    let mut prim = None;
    for attr in attrs {
        if !attr.path().is_ident("repr") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if is_prim(&meta.path) {
                prim = Some(meta.path);
            }
            Ok(())
        });
    }
```

And it seems to me the more correct way to write this would just be like so:

```rs
fn get_primitive_repr(atts: &[Attribute]) -> Result<Path> {
    let mut prim = None;
    for attr in attrs {
        if !attr.path().is_ident("repr") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if !is_prim(&meta.path) {
                return Ok(());  // Skip, not a primitive repr.
            }

            if prim.is_some() {
                return Err(Error::...);  // Error if multiple prim repr specified
            }

            prim = Some(meta.path);
            Ok(())
        })?;
    }
    prim.ok_or_else(|| Error::...)  // Error if no prim repr specified
}
```

I find this to be clearer and more explicit, but I wouldn't block on it personally.

> @trent-reed if you have time feel free to give safe-disc another look, if all looks good to you, I can put it on crates.io.

I'm good with it, we can always iterate if we find something wrong. Thanks! :)
